-- Subscriber store for the Cx interface.
--
-- Credentials are held only as realm-bound H(A1) digests; the plaintext password is
-- never persisted. The guards below let this migration adopt a schema that a previous
-- build created with Hibernate `ddl-auto: update` (see docs/TECH_DEBT.md TD-030).

CREATE TABLE IF NOT EXISTS subscriber (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    impi            varchar(255) NOT NULL,
    impu            varchar(255) NOT NULL,
    realm           varchar(255) NOT NULL,
    ha1             varchar(64)  NOT NULL,
    ha1_sha256      varchar(128),
    scscf_name      varchar(255),
    state           varchar(255) NOT NULL DEFAULT 'NOT_REGISTERED',
    service_profile text
);

ALTER TABLE subscriber ADD COLUMN IF NOT EXISTS ha1 varchar(64);
ALTER TABLE subscriber ADD COLUMN IF NOT EXISTS ha1_sha256 varchar(128);

-- The legacy plaintext credential is dropped, not migrated: rows provisioned before
-- Phase 4 carry no digest and must be re-provisioned.
ALTER TABLE subscriber DROP COLUMN IF EXISTS password;
DELETE FROM subscriber WHERE ha1 IS NULL;
ALTER TABLE subscriber ALTER COLUMN ha1 SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_subscriber_impi ON subscriber (impi);
CREATE UNIQUE INDEX IF NOT EXISTS uk_subscriber_impu ON subscriber (impu);
